# Bandit Level 2 → 3

## Objective

The password for the next level is stored in a file called `--spaces in this filename--` located in the home directory.

## Concept Tested

Shell tokenization and argument parsing, specifically handling whitespace and escaping characters in the command-line interface. 

## Initial Access

Establish an SSH session to the target host as user `bandit2`:

```bash
$ ssh bandit2@bandit.labs.overthewire.org -p 2220
bandit2@bandit.labs.overthewire.org's password: [REDACTED]
bandit2@bandit:~$
```

## Recon

To start this challenge, the contents in this directory were listed to verify the fact that the `--spaces in this filename--` file was indeed in the home directory (the current directory) and to identify ownership and POSIX mode bits.

```bash
bandit2@bandit:~$ ls -la
total 24
-rw-r-----   1 bandit3 bandit2   33 Jun 24 14:59 --spaces in this filename--
drwxr-xr-x   2 root    root    4096 Jun 24 14:59 .
drwxr-xr-x 150 root    root    4096 Jun 24 15:02 ..
-rw-r--r--   1 root    root     220 Feb 13 12:16 .bash_logout
-rw-r--r--   1 root    root    3851 Jun 24 14:50 .bashrc
-rw-r--r--   1 root    root     807 Feb 13 12:16 .profile
```

`ls -la` lists all directory contents, including hidden files, along with the file ownership and permissions bits. The output revealed that the `--spaces in this filename--` file is located in the home (current) directory. It is owned by `bandit3` and in group `bandit2`, with mode `0640` (`-rw-r-----`).
World access is fully revoked (`---`), but members of group `bandit2` hold read privilege (`r--`). Two problems jump out immediately: the name contains spaces (the shell would split this into multiple arguments if unquoted) and it starts with `--` (which `cat` and most GNU tools would try to interpret as a command-line option rather than a filename).

Just as in the previous level (`Level 1 -> 2`), one would then attempt to retrieve the password using `cat`:

```bash
bandit2@bandit:~$ cat --spaces in this filename--
error: unexpected argument '--spaces' found

  tip: to pass '--spaces' as a value, use '-- --spaces'

Usage: cat [OPTION]... [FILE]...

For more information, try '--help'.
```

But in doing so an error will appear as shown above. This error's `tip:` line reveals the correct syntax to the password.

## Solution

To read the contents of file `--spaces in this filename--` one would only need to follow the tip of the error, the format of this error also strongly suggests that it was generated by the Rust tool using the `clap` library as demonstrated in the Recon section:

```bash
bandit2@bandit:~$ cat -- '--spaces in this filename--'
[REDACTED]
```

Alternatively, one could wrap the file in quotes and direct the read function to the path of the file like this:

```bash
bandit2@bandit:~$ cat ./"--spaces in this filename--"
[REDACTED]
```
## Verification

Authenticate as `bandit3` using the retrieved password:

```bash
[Laptop-3344]:~$ ssh bandit3@bandit.labs.overthewire.org -p 2220
bandit3@bandit.labs.overthewire.org's password: [REDACTED]
bandit3@bandit:~$ whoami
bandit3
```

**Explanation:** Initiating a new SSH session to port `2220` and supplying the retrieved password at the prompt grants access. Running `whoami` and observing the updated shell prompt (`bandit3@bandit:~$`) confirms successful authentication as `bandit3`.

## Why This Works

- **Shell word-splitting**: unquoted whitespace in a command line separates arguments. Wrapping the filename in quotes (single or double) tells the shell "treat this whole string as one argument," preserving the spaces.
- **Program-level option parsing**: getopt-style argument parsers and clap-based parsers generally honor the same `--` sentinel convention and so it treats any argument starting with `-` as a flag unless told otherwise. The `--` sentinel is a widely honored convention that says "stop parsing flags, everything after this is a literal positional argument." Alternatively, prefixing with `./` changes the string itself so it no longer starts with `-`, sidestepping the flag-detection logic entirely.

## Key Takeaway

When scripting or handling user-supplied filenames, always quote variables and paths, and use `--` before filenames when calling command-line tools — this prevents both accidental word-splitting and accidental interpretation of filenames as options, which is a real source of bugs and security issues (e.g. an attacker naming a file `-rf` next to a careless `rm *` call).
## Password

`[REDACTED - see level for retrieval method]`

---
